---

- name: "Create SWITCHAAI directory in opt"
  file:
    path: "{{ shibboleth_template_repository_dest_path }}"
    state: directory
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - repository

- name: "Download SWITCH repository"
  get_url:
    url: "https://pkg.switch.ch/switchaai/debian/dists/buster/main/binary-all/misc/switchaai-apt-source_1.0.0_all.deb"
    dest: "{{ shibboleth_template_repository_dest_path }}"
  tags:
    - install
    - repository

- name: "Install SWITCHAAI reporitory"
  apt:
    deb: "{{ shibboleth_template_repository_dest_path }}/switchaai-apt-source_1.0.0_all.deb"
  tags:
    - install
    - repository

- name: Install Shibboleth
  apt:
    name: shibboleth
    state: latest
    update_cache: yes
    install_recommends: yes
  tags:
    - install

- name: Generate Shibboleth key and cert
  command: shib-keygen -h {{ shibboleth_hostname }} -e {{ shibboleth_sp_entity_id }}
  args:
    chdir: /etc/shibboleth
    creates: /etc/shibboleth/sp-key.pem
  notify:
    - "restart shibd"
  tags:
    - install

- name: Copy configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/shibboleth/{{ item }}"
  loop:
    - attribute-map.xml
    - shibboleth2.xml
  tags:
    - configuration
  notify:
    - "restart shibd"

- name: Stop Shibboleth SP
  service:
    state: stopped
    name: "shibd"
  tags:
    - never
    - stop

- name: Start Shibboleth SP
  service:
    state: started
    name: "shibd"
  tags:
    - never
    - start

- name: "flush handlers"
  meta: flush_handlers
